apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  KAFKA_HOST: cGtjLTZvanYyLnVzLXdlc3Q0LmdjcC5jb25mbHVlbnQuY2xvdWQ6OTA5Mg==
  KAFKA_CLIENT_ID: YmFja2VuZA==
  KAFKA_SASL_USERNAME: VEpGNUtTU0xIS0EyQ1VDUA==
  KAFKA_SASL_PASSWORD: QmFDY3NEcFFDcHVvbllVUkpuYkZSMWlkZlEzNWRxS2xpL0d5aUZKUkIzcVBVOVcyQ0hSL3drb3p4SC81ejZNWg==
  KAFKA_USE_SSL: dHJ1ZQ==
  DB_CONNECTION: bXlzcWw=
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: ZnV6Nlk2ZmZtWQ==
  DB_HOST: bXktcmVsZWFzZS1teXNxbA==
  DB_DATABASE: YmFja2VuZA==
  DB_PORT: MzMwNg==
